[package]
name = "as-macro"
description = "The macro library for ArtSpot."
version = { workspace = true }
edition = { workspace = true }
# TODO: Fill out the repository field to help NEAR ecosystem tools to discover your project.
# NEP-0330 is automatically implemented for all contracts built with https://github.com/near/cargo-near.
# Link to the repository will be available via `contract_source_metadata` view-function.
#repository = "https://github.com/xxx/xxx"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
syn = { version = "2", features = ["full", "parsing"] }
quote = "1.0"
darling = "*"
proc-macro2 = "*"

[dev-dependencies]
near-workspaces = { version = "0.10.0", features = ["unstable"] }
