[package]
name = "spot-token"
description = "The fungible token contract for ArtSpot."
version = { workspace = true }
edition = { workspace = true }
# TODO: Fill out the repository field to help NEAR ecosystem tools to discover your project.
# NEP-0330 is automatically implemented for all contracts built with https://github.com/near/cargo-near.
# Link to the repository will be available via `contract_source_metadata` view-function.
#repository = "https://github.com/xxx/xxx"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
near-sdk = { workspace = true }
near-contract-standards = "*"

[dev-dependencies]
anyhow = "1.0"
near-sdk = { version = "5.1.0", features = ["unit-testing"] }
near-workspaces = { version = "0.10.0",features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
